export default {
  HOME: 'home',
  HOME_TAB: 'home_tab',
  MINE: 'mine',
  MINE_TAB: 'mine_tab',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  NOT_FOUND: 'not-found',
  SETTINGS: 'settings',
  ALBUMS: 'albums',
  ALBUM_TRACKS: 'album-tracks',
  SEARCH: 'search',
  SEARCH_TAB: 'search_tab',
  PLAYLISTS: 'playlists',
  BOOKS: 'books',
  EVENTS: 'events',
  CHURCHES: 'churches',
};
